### ISSUE TITLE
Addition of Newsletter 4th edition

### ISSUE THREAD

**Issue by edenico76** [Dan5762/Imperial-Quantum-Society#14]
Hi, can you add the 4th edition from 18.2 ?
link: https://mailchi.mp/51a00931830a/quantum-technology-society-newsletter-15916487?e=4579a51b70

**Comment by h-rathee851** [comment]
@edenico76 Doesn't the CDM Allow you to edit the newsletters? If not, I think we should be able to do that.

**Comment by edenico76** [comment]
@h-rathee851 yes actually it does, I don't know if I've missed it or you guys added it now, but next time I can defo update it myself, cheers.
