### ISSUE TITLE
Change Register Now button from the upcoming events

### ISSUE THREAD

**Issue by edenico76** [Dan5762/Imperial-Quantum-Society#17]
The button is quite confusing because we want to add links for registerartion for the events themselves.

Currently I've changed the link of the event itself (when we press on the text) to be the registration link. 

Maybe we can change the Register Now button to "Register for the next event", and to add the option to edit to netlify ?

**Comment by h-rathee851** [comment]
Sure. That sounds reasonable. In fact, instead of adding it to CMS explicitly, we can have the code automatically pull the link for the latest event and add it to the button. How does that sound? @edenico76 @Dan5762 .

**Comment by edenico76** [comment]
Sounds good. Where should it pool the link from ? @h-rathee851

**Comment by h-rathee851** [comment]
@edenico76  I have changed it so that it automatically gets the link of the first event in the upcoming events list.

**Comment by edenico76** [comment]
@h-rathee851 cool, looks good, thanks !
